### ISSUE TITLE
Race condition of pool idle connection cleanup task and acquiring connection

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxNetty#100]
In the code of IdleConnectionsCleanupTask:

```
    PooledConnection<I, O> idleConnection = iterator.next(); // 1
    if (!idleConnection.isUsable()) { // 2
           iterator.remove(); 
           discardConnection(idleConnection); 
    }
```

Follow the sequence below:
1. clean up thread gets an idle connection from `iterator.next()` at mark 1
2. clean up thread gets suspended
3. another thread acquires the same connection via `idleConnections.poll()`
4. clean up thread resumes, and at mark 2 `idleConnection.isUsable()` may return false since some time has elapsed 
5. clean up thread closes the connection, which is already in use in another thread

Possibly make sense to use an AtomicBoolean to indicate that a PooledConnection has been owned by a thread?

**Comment by NiteshKant** [comment]
Good point.

Comparing it with an otherwise normally occurring scenario: 

Connection is closed by the OS when it is in use (this will primarily be due to server closing the connection).

Will the system behave any differently in these two scenarios? I believe no.

Now, can we avoid this scenario?

Let us take your possible fix. If we do have a flag "isUsed" in the connection, then the above code will convert to:

```
PooledConnection<I, O> idleConnection = iterator.next(); // 1
    if (!idleConnection.isUsable() && !idleConnection.isInUse()) { // 2
           iterator.remove(); 
           discardConnection(idleConnection); 
    }
```

(The isInUse() check can be inside isUsable() but this is just for discussion purpose)

Is the above fix any different than what is there currently? I think no because the threads can be interleaved so that the connection acquire is between isInUse() check and iterator.remove()/discard call. So it is essentially the same situation.

I think the only way we can ensure that it is not used while in the iterator loop is that instead of having an iterator, we do a drain() from the queue and then add back the connections which are usable. Considering normal usage pattern of highly used pools, I guess if this concurrency situation is to be considered, we should assume that the pool is in frequent use and hence most of the connections are _not_ idle. Hence, we should optimize for connections that are not idle for long (i.e. not expired) than the situation in which they are. The completely safe situation optimizes for the situation when most of the connections are about to be expired. The current one hopes that there are less such occurrences.

**Comment by allenxwang** [comment]
Would this fix the problem, assuming `owned` is an AtomicBoolean:

For cleaning thread:

``` java
PooledConnection<I, O> idleConnection = iterator.next(); // 1
    if (!idleConnection.isUsable() && !idleConnection.owned.compareAndSet(false, true)) { // 2
           iterator.remove(); 
           discardConnection(idleConnection); 
    }
```

For acquiring thread:

``` java
PooledConnection<I, O> idleConnection = idleConnections.poll();
        while (null != idleConnection)) {
                if (!idleConnection.isUsable()) {
                    discardConnection(idleConnection);
                    idleConnection = idleConnections.poll();
                } else if (!idleConnection.owned.compareAndSet(false, true)) {
                    // this should only happen if clean up thread has set the ownership of the connection
                    idleConnection = idleConnections.poll();
                } else {
                    break;
                }
       }
```

Any other race condition problems that are not solved after this?

**Comment by NiteshKant** [comment]
> > > Any other race condition problems that are not solved after this?

My $0.02 I do not think it is worth adding this state on the Connection as the really edge case we are trying to address is anyways going to happen. 
The usecase we are trying to solve is when a connection is about to get expired ( within ~ nanoseconds considering that we are only talking about thread interleaving) we make sure that either one of the thread; cleanup or acquirer thread gets a exclusive access to the connection.
Since, the connection is anyways about to expire and there is no way we can assure we don't use a connection which is not, this does not seem necessary. What is necessary is that our system handles such a scenario, which a system like ribbon will typically do by means of "retries on a different server". More importantly, this is anyways going to happen more often than this interleaving.

However, since this is not a big change, I would go ahead and add this safety net.
