### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by mathieucarbou** [ReactiveX/RxNetty#106]
Hello,
Does RxNetty Http client can connect to https websites ? I do not see any doc or sample relating to https.
Thank you!

**Comment by NiteshKant** [comment]
Netty supports SSL via [SSLHandler](https://github.com/netty/netty/blob/master/handler/src/main/java/io/netty/handler/ssl/SslHandler.java) so RxNetty also does support SSL.

You can create a PipelineConfigurator implementation that adds an SSLHandler in the pipeline much as [this example](https://github.com/netty/netty/tree/master/example/src/main/java/io/netty/example/securechat) in netty demonstrates. In order to understand RxNetty's PipelineConfigurators have a look at the [pipeline package](https://github.com/Netflix/RxNetty/tree/master/rx-netty/src/main/java/io/reactivex/netty/pipeline)

Having said the above, I think we should add an HTTPs example. I will add the same.

**Comment by tbak** [comment]
To add SSL/TLS support to RxNetty, the RxServer/RxClient pipeline setup must be made more flexible.

SSL handling is supported by Netty's SslHandler ChannelHandler. It enforces a three step process for full communication setup:
1. Start with basic pipeline configuration and SSL ChannelInitializer in the pipeline
2. On channel registration inject SslHandler as a first handler
3. On SslHandshakeCompletionEvent event activate RxNetty's ConnectionHandler (to ensure nothing is written to the channel prior to handshake completion)

The first two steps can be done easily now. What is less obvious is how to prevent ObservableConnection from firing write events into the channel prior to getting handshake confirmation event.

Having said that here is a working prototype for TCP protocol without waiting for handshake complete event: https://github.com/tbak/RxNetty/commit/4c55b2122e1816cf464eaca079ea5b532584844e

Any read or write to the channel will enforce handshake negotiation in a first place. I am not sure if we can rely on it, or strictly follow the rules written in SslHandler documentation.

**Comment by tbak** [comment]
First version with proper handling of the handshake event is available here: https://github.com/tbak/RxNetty/commits/features/ssl

**Comment by tbak** [comment]
SSL support is now implemented. Most of the changes are in this commit: https://github.com/Netflix/RxNetty/commit/07c39de2a9e3c8b490c1b68dd5c2462ebaf3e2ae.
