### ISSUE TITLE
HttpServerRequest.getPath returns complete URL

### ISSUE THREAD

**Issue by tbak** [ReactiveX/RxNetty#154]
Calling getPath method in HTTP hello world example returns "http://localhost:8090/hello", while it should be only "/path".

**Comment by NiteshKant** [comment]
@tbak the problem is not with the server in the helloworld example. It is with the client.
If you curl the endpoint, you will see the following output on the server:

```
New request received
GET /hello HTTP/1.1
User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8y zlib/1.2.5
Host: localhost:8090
Accept: */*
Content-Length: 0
```

whereas if you use the `HelloWorldClient` you will see the following output on the server:

```
New request received
GET http://localhost:8090/hello HTTP/1.1
Host: localhost
User-Agent: RxNetty Client
Content-Length: 0
```

Now, if you enable the wire logging for the server, the `HelloWorldClient` request shows like this:

```
ERROR [rx-selector-1-2] (Slf4JLogger.java:161) - [id: 0x6a2e2275, /127.0.0.1:61710 => /127.0.0.1:8090] RECEIVED(89B)
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 47 45 54 20 68 74 74 70 3a 2f 2f 6c 6f 63 61 6c |GET http://local|
|00000010| 68 6f 73 74 3a 38 30 39 30 2f 68 65 6c 6c 6f 20 |host:8090/hello |
|00000020| 48 54 54 50 2f 31 2e 31 0d 0a 48 6f 73 74 3a 20 |HTTP/1.1..Host: |
|00000030| 6c 6f 63 61 6c 68 6f 73 74 0d 0a 55 73 65 72 2d |localhost..User-|
|00000040| 41 67 65 6e 74 3a 20 52 78 4e 65 74 74 79 20 43 |Agent: RxNetty C|
|00000050| 6c 69 65 6e 74 0d 0a 0d 0a                      |lient....       |
+--------+-------------------------------------------------+----------------+
```

As you can see above the request generated by the client is wrong.

**Comment by tbak** [comment]
You are right. We have small inconsistency in RxNetty factory methods. They expect absolute URIs, so they can extract from them ServerInfo, but this URI is also passed in HTTP request in absolute form.

**Comment by Crystark** [comment]
+1

I just wanted to switch from ning's async-http-client to RxNetty and found out I couldn't just use my URL as i did before.
That's what I had:

``` java
this.httpClient
    .preparePost("http://server/myendpoint")
    .addHeader(HttpHeaders.CONTENT_TYPE, ContentTypes.JSON.getMimeType())
    .setBody(JsonTranslator.toJson(obj))
    .execute();
```

And I tried to replace it with the quite similar:

``` java
RxNetty
    .createHttpRequest(HttpClientRequest
        .createPost("http://server/myendpoint")
        .withHeader(HttpHeaders.CONTENT_TYPE, ContentTypes.JSON.getMimeType())
        .withContent(JsonTranslator.toJson(obj))
    )
```

But I ran into that problem: the received URI is `http://server/myendpoint` instead of the expected `myendpoint`.
Any plans on fixing this ? Or at least a workaround that doesn't require me parsing the input URL ?

Thanks

**Comment by NiteshKant** [comment]
@Crystark passing the host in the URI works only for "external" endpoints or endpoints published via DNS. For target servers that are discovered via service discovery in microservices based architectures, usually use a client-side load balancer to choose the best host for a request and the URIs are just relative (excluding the scheme, host and port info).

For this reason, in the [next release (0.5.0)](https://github.com/ReactiveX/RxNetty/wiki/0.5.x-FAQs), we have removed this functionality of passing a dynamic host/port in the URI. Instead that is handled via a `ConnectionProvider` abstraction. This makes the usage consistent that the target servers are homogeneous and fixed for a client.

So, the way to use `HttpClient` will always be by means of specifying relative URIs (no scheme, host & port) and specify the host or a pool of hosts while creation.

**Comment by Crystark** [comment]
@NiteshKant Just so i'm sure I understand what you're saying, you're completely removing the ability for someone to create an http request using an absolute URI ? I understand your point and I don't mind adapting my code to that but that means you're dropping the convenient helpers that allow you to easily call an "external" endpoint. Why not keep that so that anyone who wants to switch to RxNetty as their HttpClient can do so without having to rewrite more than their external service class ?

It looks to me like it's a pretty common use case. At least that's what I wanted to do. Or am I missing something here ?

**Comment by NiteshKant** [comment]
@Crystark apologies for the delayed response.

There are more than what meets the eye here. A client in `RxNetty` holds obvious state for a host like connection pool and subtle state like caching of request observable, metrics, etc. If it is allowed to specify arbitrary host in the URL, then we either have to maintain this state per each random host specified or choose not to follow the other aspects specified with the client. Additionally, what happens if the client is created with a load balancer, clearly the load balancer is of no use in this scenario.

Broadly speaking, the option to provide the server's address both in the URI and while client creation, creates ambiguities (like above) and does not really give any advantages. This is the reason, we have stuck to a single mode of specifying the target server address(s) at the client creation time as opposed to request submission time. IMO, this makes the usage consistent and reduces ambiguities.

**Comment by Crystark** [comment]
@NiteshKant OK I can understand that. Thanks for taking the time of explaining this to me.
