### ISSUE TITLE
Consuming response of type ByteBuf in a different thread will fail

### ISSUE THREAD

**Issue by g9yuayon** [ReactiveX/RxNetty#203]
Below is the code that reproduces the problem. Consuming a ByteBuf response in a different thread from the event loop's will result in the IllegalReferenceCountException. This is usually okay if a user expects ByteBuf as the raw response. However, if a user wraps RxNetty client in a library that supports generics, then the user will run into this problem unless she inspects the type of each response and call ByteBuf#retain().

``` java
package io.mantisrx.runtime.source.http.impl;

import io.netty.buffer.ByteBuf;
import io.netty.handler.codec.http.HttpResponseStatus;
import io.reactivex.netty.RxNetty;
import io.reactivex.netty.protocol.http.client.HttpClientResponse;
import io.reactivex.netty.protocol.http.server.HttpServer;
import rx.Observable;
import rx.schedulers.Schedulers;

import java.nio.charset.Charset;

public class Test {

    public static void main(String[] args) throws Exception {
        for(int i = 0; i <= 2; ++i) {
            int port = 8080 +i;
            HttpServer<ByteBuf, ByteBuf> server = RxNetty.createHttpServer(port, (request, response) -> {
                System.out.println("Server => Request: " + request.getPath());
                try {
                    if ("/error".equals(request.getPath())) {
                        throw new RuntimeException("forced error");
                    }
                    response.setStatus(HttpResponseStatus.OK);
                    response.writeString("Path Requested for port "+port+" =>: " + request.getPath() + '\n');
                    return response.close();
                } catch (Throwable e) {
                    System.err.println("Server => Error [" + request.getPath() + "] => " + e);
                    response.setStatus(HttpResponseStatus.BAD_REQUEST);
                    response.writeString("Error 500: Bad Request\n");
                    return response.close();
                }
            });

            server.start();
        }

        Observable.from(8080, 8081, 8082)
            .flatMap(
                port -> RxNetty
                    .createHttpGet("http://localhost:" + port)
                    .flatMap(HttpClientResponse::getContent)
            )
            .observeOn(Schedulers.newThread())
            .doOnNext((s) -> {
                new Thread(() -> {
                    System.out.println("Got it ==> " + s.toString(Charset.defaultCharset()));
                }).run();
            })
            .doOnError(Throwable::printStackTrace) // <<== This line will print out the exception
           .subscribe();

        Thread.sleep(5000);
    }
}
```

**Comment by NiteshKant** [comment]
@g9yuayon the reason why this happens is because RxNetty releases the `ByteBuf` after the `onNext()` call which alleviates the client of the overhead of managing `ByteBuf`'s lifecycle management (which is required as `ByteBuf`s are off heap and are not managed by the garbage collector). However, it fails in the case where the scope of `ByteBuf` extends the scope of `onNext()` as in this case.

I agree that this is rather inconvenient. There are a few possible solutions:
1. Have a client option (per client or per request but not global) that disables auto-release by RxNetty  and hence it becomes the responsibility of the eventual `ByteBuf` consumer to release the `ByteBuf` after it has been consumed.
2. In order to hide the whole complexity of `ByteBuf` management in async subscriptions, we can provide an operator (to be used instead of `observeOn()`) which does the correct thing i.e. `ByteBuf.retain()` when it receives an `onNext()` and `ByteBuf.release()` when the `onNext()` sent by the underlying `Scheduler` is done.
3. The client can use netty's utility class: `ReferenceCountUtil` to `retain` and `release` at appropriate places described in 2 above. That utility class takes any type argument and does the needful only if the argument is a `ReferenceCounted` instance.

I find 2 above to be too limiting as it can not interplay with the existing `observeOn` semantics.
1 is easy to do with the current `ClientConfig` semantics.
You can use 3 to make the process a little bit compact for now.

@benjchristensen @mattrjacobs since you guys also bumped into this in Zuul, any thoughts?

**Comment by benjchristensen** [comment]
(1) is so nuanced that people will still run into this.
(2) is not a valid option. It will be too confusing.

Someone should only have to deal with this stuff if interacting with ByteBuf directly. So what's the story once we have the serialization hooks?

Using ByteBuf means a user must deal with Netty semantics. This should be transparent and very clearly documented.

The normal cases though where Strings, JSON, XML, pick-your-format is being used this should all become hidden.

Thus, Zuul will need to deal with it since it does in fact want to work with ByteBuf. Most HTTP client/server implementations though do not (unless it's a file server just doing raw bytes).

We don't want to hide the power and performance of Netty when it's wanted, but the typical cases should be made easier since that's the point of RxNetty. We should have a "pit of success" where doing the normal thing of getting a String back (the majority of HTTP code I've ever seen) "just works" and dropping down to ByteBuf is a choice a developer makes along with the more nuanced behavior.

**Comment by alexwen** [comment]
The work around ATM for this issue, I am not sure about the overall best scenario for API users, is for the consumer to retain the reference to the ByteBuf (taking it over from RxNetty). I do this by using an Operator:

```
final Observable<ByteBuf> content = request.getContent().lift(NettyOperators.refBuffer());
```

Here is the Operator:

```
    private static final Observable.Operator<ByteBuf, ByteBuf> REF_BUFFER = NettyOperators::refBuffer;

    public static Observable.Operator<ByteBuf, ByteBuf> refBuffer() {
        return REF_BUFFER;
    }

    private static Subscriber<ByteBuf> refBuffer(final Subscriber<? super ByteBuf> child) {
        return new Subscriber<ByteBuf>() {
            @Override
            public void onCompleted() {
                child.onCompleted();
            }

            @Override
            public void onError(Throwable e) {
                child.onError(e);
            }

            @Override
            public void onNext(ByteBuf buffer) {
                if (!child.isUnsubscribed()) {
                    buffer.retain();
                    add(new BufferSubscription(buffer));

                    child.onNext(buffer);
                }
            }
        };
    }

    private static class BufferSubscription implements Subscription {
        private final ByteBuf buffer;
        private final AtomicBoolean unsubscibed = new AtomicBoolean(false);

        public BufferSubscription(ByteBuf buffer) {
            this.buffer = buffer;
        }

        @Override
        public void unsubscribe() {
            if (unsubscibed.compareAndSet(false, true)) {
                buffer.release();
            }
        }

        @Override
        public boolean isUnsubscribed() {
            return unsubscibed.get();
        }
    }
}
```

**Comment by NiteshKant** [comment]
0.5.x has on-demand read (#324) and no auto-release of `ByteBuf`, so a receiver can hold on to the `ByteBuf` as long as it wants.
