### ISSUE TITLE
Hardcoded stuff in HttpClientImpl prevents the usage of https

### ISSUE THREAD

**Issue by bobymicroby** [ReactiveX/RxNetty#213]
Guys..the issue is invalid. 

The problem was that we needed custom SslFactory in order to  sslEngine.setUseClientMode(true);  We taught that if we are in client mode this will be set automatically. There was no exception, no timeout just waiting for the handshake to begin and that never happend...

**Comment by tbak** [comment]
You made a good point there is a bug in HttpClientRequest where the absolute URI is not reconstructed properly. I can see in the code that this absolute URI value is used only by HTTP redirect logic, to track infinite loops. It should not have any visible effects.

The decision about using SSL (at least now) does not come from URI but the proper pipeline configuration. In most cases the usage pattern is:

``` java
HttpClient<ByteBuf, ByteBuf> rxClient = RxNetty.<ByteBuf, ByteBuf>newHttpClientBuilder("localhost", port)
                .withSslEngineFactory(DefaultFactories.TRUST_ALL)
                .build();

        HttpResponseStatus statusCode = rxClient.submit(HttpClientRequest.createGet("/hello"))
```

As you can see absolute URI is not passed here.

The issue is with RxNetty.createHttp... methods:

``` java
RxNetty.createHttpGet("https://abc.com/");
```

In this case, server (abc.com) and port (default HTTPs 443) values will be extracted properly from URI, but the pipeline will not be automatically updated to include SSL as well. This is obviously a bug, and we will have to fix this.

**Comment by tbak** [comment]
I am looking at this and we have basically 3 cases:

1) `RxNetty.newHttpServerBuilder` - the properly working now:
Here user creates client directly with proper pipeline, and deals only with relative URIs

2) `RxNetty.createHttpClient(host, port)` - easy to fix
We could add an extra method:

``` java
RxNetty.createHttpClient(host, port, withSsl)
```

3) `RxNetty.createHttpRequest` + createHttpGet, etc

Here we are using `CompositeHttpClient` and `RxNetty.globalClient`. The request execution is handled in the following way:

``` java
    public static Observable<HttpClientResponse<ByteBuf>> createHttpRequest(
                 HttpClientRequest<ByteBuf> request) {
        RxClient.ServerInfo serverInfo;
        try {
            serverInfo = getServerInfoFromRequest(request);
        } catch (URISyntaxException e) {
            return Observable.error(e);
        }
        return globalClient.submit(serverInfo, request);
    }

    public static Observable<HttpClientResponse<ByteBuf>> createHttpRequest(
           HttpClientRequest<ByteBuf> request,
           HttpClient.HttpClientConfig config) {
        RxClient.ServerInfo serverInfo;
        try {
            serverInfo = getServerInfoFromRequest(request);
        } catch (URISyntaxException e) {
            return Observable.error(e);
        }
        return globalClient.submit(serverInfo, request, config);
    }
```

We could add SSL flag to `HttpClient.HttpClientConfig`, and set it properly when parsing absolute URI from a client. In the composite client we would have to distinguish between HTTP/HTTPs endpoints of the same server.

**Comment by bobymicroby** [comment]
Nice to hear that. We will keep you posted about our future(Observable) endeavours . Next time I hope we will prepare a PR and not just open and close a ticket. Best of luck to you and your team. Regards, B.

**Comment by NiteshKant** [comment]
`RxNetty.createHttpGet` methods had various limitations and has been removed in 0.5.x. I believe this issue would not exist with 0.5.x, if it does, please reopen
