### ISSUE TITLE
ObservableConnection vs ObservableHttpResponse

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxNetty#4]
Does it continue to make sense giving HTTP it's own response type instead of the generic `ObservableConnection`?

Thinking more since yesterday I think it probably still does because HTTP is such a common protocol and different from the others in that it is unidirectional once established.

I do think though we should make sure `ObservableConnection` and `ObservableHttpResponse` feel similar.

**Comment by NiteshKant** [comment]
How I look at it, this is how the abstractions are:

1) Connection
2) Request
3) Response

Both TCP & HTTP have a connection that can be used to send one or more request responses (ignoring HTTP 1.0 where you can only send 1 request on a connection).
HTTP 1.1 limits the responses to be sequential or ordered i.e. the response of the first request should be sent before the response to the second (HTTP pipelining). In TCP there is no such restriction but it depends on the application level protocol how you choose to co-relate request & response.

Additionally, HTTP response can be broken into two or more parts:

1) Headers
2) Content: 1 or more.

What it looks to me is that HTTP response would need a differentiation in the above respect that the response itself has two events but it is built on top of connection. So, the ObservableConnection for HTTP should return a Observable&lt;HTTPResponse&lt;T>> from getInput().
On top of this for HTTP if you are reusing connections, you would have to provide a response end event too, I am not sure whether it is done now or not.

Is this what you meant by them being similar?

**Comment by g9yuayon** [comment]
Yeah, we should keep ObservableHttpResponse (or something similar) for the reason that an HTTP response contains both headers and content. Since there can be more than one content per response, we can model the content as an observable. That's exactly what ObservableHttpResponse does. 

I'm not sure if we can directly use ObservableConnection as HTTP client. In theory, we could have this type for an HTTP client: ObservableConnection&lt;ObserbableHttpResponse&lt;T>, HttpRequest>, but a TCP connection itself does not require pipelining, so it becomes an implicit assumption that we should expect that getInput() returns the response of last request. In contrast, an HTTP client makes the assumption of pipelining explicit: if we execute a request, we will get back the corresponding request wrapped in an observable. Therefore, it looks to me that it make sense to provide an abstraction for http client in RxNetty.

**Comment by g9yuayon** [comment]
By the way I updated Nitesh's comment slightly by replacing the left angle bracket &lt; with &lt;, otherwise github will hide the character.

**Comment by NiteshKant** [comment]
Thanks Danny for updating my comment!
Actually you do not need to expose the abstraction of HTTPClient to the users. Internally Rx can make sure that the connection is reused only when the previous request is over & there isn't anymore subs alive. So, the abstraction becomes consistent irrespective of the protocol. 
Rx should possibly disallow pipelining by clients to avoid the overhead of request-response-subscriber correlation for HTTP.

**Comment by NiteshKant** [comment]
With this refactoring: https://github.com/Netflix/RxNetty/pull/19

RxClient provides a connect method which returns Observable<ObservableConnection>.
HttpClient uses this connect method and converts ObservableConnection.getInput() to Observable<ObservableHttpResponse>.
This makes the overall experience interacting with RxNetty for clients, consistent.

I am closing this issue.
