### ISSUE TITLE
(0.4.11)  HttpClientRequest.withContentSource doesn't concatenate from a HttpClientReponse.getContent

### ISSUE THREAD

**Issue by gfrison** [ReactiveX/RxNetty#418]
Hello,

I have a problem with _0.4.11_ on concatenating a response to a subsequent request.

https://gist.github.com/gfrison/ef9d9f36151234cf7f14

when I concatenate the chained request with:

``` java
post.withContentSource(Observable.just(Unpooled.copiedBuffer(header)).concatWith(response.getContent()).concatWith(Observable.just(Unpooled.copiedBuffer(footer))));
```

the `response.getContent()` doesn't flush anything.
If I replace it with an custom byte arrya that content will be flushed into the second request.

Could you please point me what is wrong?

Thank you so much,

**Comment by NiteshKant** [comment]
@gfrison I did look at your code when you referenced it in the other issue. For some reason, `response.getContent()` isn't getting completed and hence the request does not get written completely. I need to look at it more to find a reason why this is happening.

**Comment by NiteshKant** [comment]
@gfrison the issue here is that the code is subscribing to the server request content stream lazily, which produces an error. The reason why you do not see that error is because of the issue #419 I just created. If you want to do something like this in 0.4.x, it is a bigger exercise of caching content eagerly as @Crystark mentions in issue #405. In case, this is a new piece of code you are writing, I would encourage using 0.5.x instead.

**Comment by gfrison** [comment]
Hello,

the #419 has been solved but unfortunately I have still the same problem. I tested against 0.4.13, what can I do to solve this problem?

Thank you,

**Comment by NiteshKant** [comment]
@gfrison #419 was to bubble the error up to you, an absence of which gave a "hung state" impression. 

The basic issue is that by the time, the client subscribes to the content stream from the server request, it is discarded. You will have to solve this by caching the content eagerly. Similar discussion is happening in the issue I pointed to, in my earlier comment.
