### ISSUE TITLE
PoolExhaustedException Resolution

### ISSUE THREAD

**Issue by dfjones** [ReactiveX/RxNetty#434]
I've noticed that it can be easy to generate a spike of requests and exhaust the connection pool (this is a project using Netflix Ribbon, with the default per host connection pool size of 50). I'm wondering what techniques can be used to avoid immediate failure in this case.

Is there a straightforward way to have a request queue up and wait for a connection to be freed? 

Thanks to Ribbon/Hystrix, these requests will eventually timeout if they are queued for too long. So, I'd prefer to have them try and acquire a connection up to their timeout rather than fail when they can't immediately acquire a connection.

Alternatively, is there a simple recipe to limit the concurrency from code that is generating the requests?

Imagine a situation like this:

``` java
obs.flatMap((a) ->
  getListForA(a)
    .flatMap((b) -> getDataForB(b))
);
```

So we'd have `count(A) * count(B)` requests in flight, which is enough to exhaust the connection pool in a cluster with a small number of servers. If there were an easy way to specify a max concurrent fanout, I think that would be very useful.

**Comment by NiteshKant** [comment]
You mentioned that you use Hystrix. The best way is to define a threadpool/semaphore limit in hystrix to limit concurrency to a client.

**Comment by dfjones** [comment]
@NiteshKant Thank you for the response. I think I see now that the issue we are running into is due to default values that don't make sense for our cluster. With the defaults in Ribbon, we are able to hit the per-host limit before the max total in most cases.

**Comment by NiteshKant** [comment]
Cool, should I close this issue then?

**Comment by dfjones** [comment]
@NiteshKant Sure. If I come up with follow-up questions, I'll just re-open this issue. (Unless there is a better means for getting questions answered?)

**Comment by NiteshKant** [comment]
I will leave this open for now and yeah this is the best place in the world to ask questions about RxNetty :)

**Comment by jonasthall** [comment]
Would it make sense to have a PooledConnectionProvider implementation which provides a connection as soon as one is released, instead of throwing a PoolExhaustedException?

**Comment by NiteshKant** [comment]
@jonasthall such an approach would introduce unpredictable delays in request processing. It is usually better to get feedbacks around limits like these as soon as possible as opposed to introduce queuing.

Usually, you should have some sort concurrency control at a higher level and the connection limits should be higher than those concurrency limits, so that connection pool limits are not reached but still are bounded. Netflix uses Hystrix for such concurrency control.

Having said the above, if you think it makes sense, you can certainly write a provider (using the existing code) to provide such a behavior.

**Comment by NiteshKant** [comment]
Closing this now.
