### ISSUE TITLE
TcpClient hangs

### ISSUE THREAD

**Issue by krisskross** [ReactiveX/RxNetty#448]
I wrote a simple ping-pong using 0.4.0 TcpClient and TcpServer.

But for some reason the client hangs _sometimes_ waiting for a response from the server. So there seems to be some race condition, but I can't figure out where?

https://gist.github.com/krisskross/101da299350eca6bae85

**Comment by krisskross** [comment]
I changed the echo example to use ByteBufs instead of Strings and the client hangs in a similar way.

**Comment by krisskross** [comment]
I got my ping-pong test working. It was a misunderstanding of RxJava on my part that caused the client to hang.

**Comment by krisskross** [comment]
I have tried a few different ways of implementing a synchronous request response. But the most intuitive and simple code I can think of hangs. Grateful for an explanation of why this code doesn't work.

https://gist.github.com/krisskross/70c4c425d3ef82a3be51

**Comment by NiteshKant** [comment]
@krisskross there is an inherent race-condition between write and read in your code. It may so happen that the reply on the connection arrives before the input is subscribed. If that happens, the `connection.getInput()` would not receive any data, as RxNetty does not cache any data read from the channel.

The best way to do it with 0.4.x (since it does not support `write(Observable)`) is to have readers and writers as totally decoupled and have a strategy for request-response correlation. eg: ordered replies, request Id in response, etc.

In 0.5.x, you can write a stream of data and merge it with the input to get the output in order.

**Comment by NiteshKant** [comment]
Thinking about it more, this will be closer to what you are trying to achieve:

``` java
        ObservableConnection<ByteBuf, ByteBuf> connection = RxNetty.createTcpClient("localhost", 1111)
                                                                   .connect()
                                                                   .toBlocking()
                                                                   .first();
        for (int i = 0; i < 10000; i++) {
            TestSubscriber<ByteBuf> outSub = new TestSubscriber<>();
            connection.getInput()
                      .map(Unpooled::copiedBuffer)
                      .take(1)
                      .subscribe(outSub);

            ByteBuf req = Unpooled.buffer().writeInt(i);
            connection.writeAndFlush(req).subscribe();

            outSub.awaitTerminalEvent();
            outSub.assertNoErrors();

            System.out.println("Iteration: " + i + ", Result " + outSub.getOnNextEvents().get(0));
        }
```

and it does not have that race-condition as the input is subscribed before the write.

**Comment by krisskross** [comment]
So the input does not cache the items. The race condition make sense to me now. 

I guess the following code would to more or less the same thing then for a single threaded ordered reply strategy.

``` java
BlockingDeque<ByteBuf> deque = new LinkedBlockingDeque<>(1);
for (int i = 0; i < 10000; i++) {
  connection.getInput()
    .map(Unpooled::copiedBuffer)
    .take(1)
    .subscribe(deque::offer);

  ByteBuf req = Unpooled.buffer().writeInt(i);
  connection.writeAndFlush(req).subscribe();
  ByteBuf res = deque.take();
}
```

I noticed that the input is a `SerializedSubject` - how does that work with multiple threads? Is it safe to have a thread local Subscribers on a shared input subject?

**Comment by NiteshKant** [comment]
Yeah the code is more or less what I put in the my last comment using a `TestSubscriber`!

> > > I noticed that the input is a SerializedSubject - how does that work with multiple threads? 

`SerializedSubject` is to serialize `on*()` calls to the `Subject` so if two threads call `onNext()` concurrently, the subscribers of this subject would not get concurrent `onNext()` invocations (illegal as per Rx contract). Since, `on*()` on this `Subject` is always called by `RxNetty`, the users must not worry about it.

> > > Is it safe to have a thread local Subscribers on a shared input subject?

In 0.4.x yes you can have multiple subscribers to the connection input, but with 0.5.x it is not allowed to have multiple concurrent subscriptions primarily because it breaks back pressure.

**Comment by krisskross** [comment]
Ok thanks Nitesh!
