### ISSUE TITLE
Possible Connection Leak and wrong metrics

### ISSUE THREAD

**Issue by soemeier** [ReactiveX/RxNetty#523]
We have experienced some Connection leak problems when using Ribbon together with rxNetty. After some analysis we found the root cause. The load balancer took out one of the servers which lead to the connection pool to be closed (`ConnectionPoolImpl.shutdown()`).

Because the connection pool got closed the isDone Flag in the `SafeListener` was set to true. When the connection that were still in use were put back to the pool the metrics were not counted anymore. 

Therefore the liveConnections counter was not reduced but which was even worse the limitDeterminationStrategy did not not reduce the number of used connections. At some point we got PoolExaustedException. 

For me the question is how to fix this problem. I did not fully understand why the metrics are not allowed to be submitted anymore once the pool is shut down. So one option for me would be to always submit the metrics. But there is probably a reason for that.

Another option for me would be to call the `onCompleted()` on the `metricsEventsSubject` only if all connections have been returned.

I would be happy to provide a fix but I am not sure which direction is the best way to go.

**Comment by NiteshKant** [comment]
> > Another option for me would be to call the onCompleted() on the metricsEventsSubject only if all connections have been returned.

@soemeier I think this would be the correct way. The metrics listener are sent an `onComplete()` as some listeners may hold state and `onComplete()` is a way to cleanup the state. I will be happy to look at your proposal to fix this. If you need help, let me know!

> > Therefore the liveConnections counter was not reduced but which was even worse the limitDeterminationStrategy did not not reduce the number of used connections. At some point we got PoolExaustedException.

Ideally `acquire()` should fail if the pool is shutdown, but I see a case where if the `Observable` returned by `acquire()` is subscribed post `shutdown`, it will not reject. May be we should fix that too.
Otherwise, these things look contradictory, if the pool is shutdown, you must not get `PoolExhaustedException` as one should never acquire post shutdown.

**Comment by NiteshKant** [comment]
Fixed via #525
