### ISSUE TITLE
Sending httpresponse in a different thread

### ISSUE THREAD

**Issue by TysonHeart** [ReactiveX/RxNetty#533]
Hi Guys, 
Looking for an answer to a question for what I believe is  simple enough async use case - accept content from http POST client and insert it into a messaging queue. The messaging queue provides an async API `send(mycallback, data)` wherein it acknowledges the receipt of data by calling `mycallback` in its own background thread. The code looks something like this:

```
HttpServer<ByteBuf, ByteBuf> server =
                RxNetty.createHttpServer(listenPort,
                        (req, resp) -> req.getContent()
                                .flatMap(content -> {
                                    RxBus<ByteBuf, InternalResponse> rxBus = new RxBus<>();
                                    String data = content.toString(Charset.defaultCharset());
                                    MessageQueue.send(mycallback, data);
                                    return rxBus.toObserverable();
                                })
                                .flatMap(internalResponse -> {
                                    resp.setStatus(internalResponse.getHttpResponseStatus());
                                    resp.writeString(internalResponse.getResponseMessage());
                                    return resp.close(true);
                                }));
HttpServerListener listener = factory.forHttpServer(server);
        server.subscribe(listener);
        System.out.println("Gateway started...");
        server.startAndWait();

```

Where RxBus is just a PublishSubject used in the mycallback. I am using this Subject to communicate the async response from the MessageQueue. One Subject per request. TBH, I got this piece from googling  around for communicating between threads.

```
public class RxBus<T1, T2> {

    private final Subject<T1, T2> _bus = new SerializedSubject(PublishSubject.create());

    public void send(T1 o) {
        _bus.onNext(o);
    }
    public Observable<T2> toObserverable() {
        return _bus;
    }
}
```

The `mycallback` simply does a `rxBus.send(internalResponse);` which simply calls `onNext()` as above.

So as is evident, the last flatmap is invoked in the MessageQueue's background thread, meaning the response object is written to and flushed in the background thread. Besides loading the background thread with unnecessary work, I am not sure it is ok technically to do this task in external thread (although it works). If I use observeOn(Schedulers.io()) just before the last flatmap, the response is sent on the io threads but these threads never get released, so it ends up using new threads till I get a OOM. I don't understand this behavior. 
I really hope to get some answers here, have spent a good part of a week trying to figure this out to no avail. If there is a better approach for this kind of use case, I am all ears. :)

**Comment by jamesgorman2** [comment]
Hey Tyson,

my first bet is a missing `onCompleted` during the send callback. If this is missing the RX job on the IO thread will hang waiting for more events and will cause thread leaks. Code below.

There's no need to push control back to an RX Scheduler. RxNetty will buffer up your writes (cheaply) in the MQ's thread then send them on it's own EventLoop thread. The only time you'd want to swap threads is if the code after the send was very expensive to run.

In terms of code style you could also make RxBus an Obserable. This would make it easier to decouple your code for testing later. (also below - I've not run this code or even put it through an IDE but you should get the idea. The callback in `super(...)` is the same as you would put in `Observable.create(...)` to create an anonymous Observer.

You should also aggregate the content in case it comes in more than one block - there is a collector in the 0.5.x branch  you can use https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-common/src/main/java/io/reactivex/netty/util/CollectBytes.java

James

```
public class RxBus<T1, T2> {

    private final Subject<T1, T2> _bus = new SerializedSubject(PublishSubject.create());

    public void send(T1 o) { // this should probably be sendComplete or something like that
        _bus.onNext(o);
        _bus.onCompleted(); // let #io() know there are no more messages
    }
    public Observable<T2> toObserverable() {
        return _bus;
    }
}
```

```
// A replayable bus request
public class RxBusRequest extend Observable<InternalResponse> {
  public RxBusRequest(MessageBus bus, String data) {
    super(subscriber ->
      try {
        bus.send(
          internalReponse -> {
            subscriber.onNext(internalReponse);
            subscriber.onCompleted();
          }
          data
        );
      } catch (Exception e) {
        subscriber.onError(e);
      }
    );
  }
}
```

**Comment by TysonHeart** [comment]
Hi James,
- adding `onCompleted()` indeed fixed the leaks. :)
- I agree, the approach to have a RxBusRequest is cleaner. I gave it a try and it works like a charm.
- Regarding this:

> There's no need to push control back to an RX Scheduler. RxNetty will buffer up your writes (cheaply) in the MQ's thread then send them on it's own EventLoop thread.

The `MessageQueue.send(,)` call is a 3rdparty API that does not use Netty/RxNetty underneath, nor does it expose its channel/socket. So I don't think Netty can buffer the writes there.
Please correct me if this logic is incorrect. 
- Collecting all bytebufs for chunked incoming data: Indeed, this is a use case I would have bumped into sooner so thanks for pointing out that. I will take a look at the ByteBuf collector you linked to.

Thank you for the directions. Helps a novice like me to appreciate and leverage the work put in. If only, RxNetty had better documentation, its adoption would be much easier. :)

**Comment by jamesgorman2** [comment]
No worries Tyson,

it looks like we're talking a little at cross purposes, but this stuff only makes sense once you know it :-) 

To simplify things we'll pretend that RxNetty is only working on a single thread, and MessageQueue on another.[1] 
- In bound HTTP requests are recieved on RxNetty's thread, where they are converted into MQ send objects.[2] 
- MessageQueue then takes that object, moves it to it's own thread then writes the object.[3] It waits for the queue response on the MessageQueue. 
- Once the queue has responded it will execute the callback:
  - `resp.setStatus(...)` and `resp.writeString(...)` and `resp.close(...)` modify the state of an object that both RxNetty's thread and MessageQueue's thread can see.[4] Since RxJava runs single threaded by default these calls are executed on MessageQueue's thread.
  - The HTTP response is not sent on the MessageQueue thread. When these calls are made, new jobs are placed on RxNetty's event loop to start sending the HTTP response.
- RxNetty sends the HTTP response data it has received on it's own thread

```
Threads
-------
RxNetty                         MessageQueue
=================================================

receive HTTP request
      |
      V
create MQ message
      |
      V
buffer MQ message for send
      +------------------------> send message

await new work
                                 await ack/response
                                      |
                                      V
                                 receive ack
                                      |
                                      V
                                 buffer HTTP headers
                                      |
send HTTP headers <-------------------+ 
      |                               V
      |                          buffer HTTP body
      V                               |
send HTTP body <----------------------+ 
      |                               V
      |                          close response
      V                               |
close connection <--------------------+
```

---

Looking back you do have another leak point - `content` is a `ByteBuf` and these need to be released manually to properly de-allocate memory by calling `content#release()`. If you search through the issues here you can see several posts by Nitesh on this.

---

[1] in real life these are both using using a pool of threads to do the work. 
[2] RX and Netty, the underlying technologies of RxNetty, both use Event Loops to run things. The best explanations I've seen are about JavaScript, which also runs on an event loop, eg http://2014.jsconf.eu/speakers/philip-roberts-what-the-heck-is-the-event-loop-anyway.html 
[3] I'm being deliberately vague about what is happening here since I don't know how Message queue is buffering/sending internally
[4] this is what I'm referring to a buffering - the callback is buffering bytes for RxNetty to send

**Comment by TysonHeart** [comment]
Hi James, that diagram and explanation certainly helped along with a lot of reading since your response. Many thanks for that.

Regarding the memory leak: I looked at #466, #357 and see that they are all fixed and closed. I am using netty's leak detector too in paranoid mode and it has NOT pointed out any leak yet but I will keep an eye. Really happy with my http server so far. :)

**Comment by NiteshKant** [comment]
@jamesgorman2 great to see awesome answer from you here!

@TysonHeart looks like you are satisfied with the explanation here?

**Comment by TysonHeart** [comment]
@NiteshKant Yes, indeed.

**Comment by NiteshKant** [comment]
Thanks @jamesgorman2 and @TysonHeart , closing this now.
