### ISSUE TITLE
RxNetty making HTTP requests with url and ServerInfo

### ISSUE THREAD

**Issue by groodt** [ReactiveX/RxNetty#549]
I'm looking into using RxNetty, and I want to clarify my understanding around making requests.

Step 1:
Obtain an httpClient. I do this like this:https://github.com/ReactiveX/RxNetty/issues/548 and pass the singleton reference to my constructor for use as below.

```
        // HTTP Request
        HttpClientRequest<ByteBuf> request = HttpClientRequest.<ByteBuf>createGet(url)
                .withHeader(HEADER_APP_ID, appId)
                .withHeader(HEADER_APP_KEY, appKey);

        RxClient.ServerInfo serverInfo;
        try {
            serverInfo = getServerInfoFromRequest(request);
            log.debug("Making request to server: {}", serverInfo);
        } catch (URISyntaxException use) {
            return Observable.error(use);
        }

        // Submit Request
        Observable<HttpClientResponse<ByteBuf>> response = httpClient.submit(serverInfo, request);
```

Step 2:
I then create an HttpClientRequest object for a url String. Right now, I'm using the full url string. Is this correct? Or should I only be using the path? Since RxNetty seems to pin an httpClient instance to a host:port anyway, regardless of the url. It is unable to make requests to new hosts dynamically unless I dynamically create new httpClient instances for every host. Correct me if I'm wrong here please. :)

Step 3:
I then extract a ServerInfo object out of the url myself, by parsing the url into a host and a port with some defaulting to 80 or 443 if required. Seems like boiler-plate that should be somewhere in RxNetty?

Step 4:
I then submit a request to my client from Step 1 and supply the request and ServerInfo from Step 2 and Step 3.

There seems to be a lot of redundancy here and I'm wondering if I'm doing things correctly, or if there is a specific rationale for things to work this way? I'm using RxNetty 0.4.x and this code does appear to be working fine, but I still wanted to ask to clarify if it is the best way to do things?
1. If I'm pinning my client to a (scheme, host, port) when I create it. Then why do I need to specify the ServerInfo again when submitting a request?
2. If I'm creating an HttpClientRequest, should I be creating it with the full url? Even though the client is already pinned to the (scheme, host, port)? If it's ignoring the (scheme, host, port), then should the API not be using the path instead.
3. Nitesh mentioned here: https://groups.google.com/forum/#!topic/rxjava/xv_W3uIhvM8 that things would improve in 0.5.x and this sounds like it would remove Step 3 above and turn the 4 Step process into a 3 Step process?

**Comment by NiteshKant** [comment]
> > > Right now, I'm using the full url string. Is this correct?

No you do not need to pass the host, port information in the client if you created a client for a host, port. [This example](https://github.com/ReactiveX/RxNetty/blob/0.4.x/rxnetty-examples/src/main/java/io/reactivex/netty/examples/http/sse/HttpSseClient.java#L50) uses this pattern.

> > > this sounds like it would remove Step 3 above and turn the 4 Step process into a 3 Step process?

RxNetty does not provide request invocations with full URLs in any of the versions. The reason is as I specified in the RxJava email thread. 0.5.x is better as opposed to 0.4.x as it introduces the concept of creating a client for a homogeneous cluster of servers as opposed to a single server in 0.4.x. This removes the boiler-plate code when using a client for a cluster.

If you see [this example](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-examples/src/main/java/io/reactivex/netty/examples/http/loadbalancing/HttpLoadBalancingClient.java) in 0.5.x and compare it with what you have, I would say the code you would have to write is only the business logic. If not, I am open to suggestions on improving the API.

**Comment by groodt** [comment]
Thanks @NiteshKant It is now clearer to me how to use RxNetty clients. For the simple case, you create an HttpClient against the host:port and then make requests to paths on that host.
