### ISSUE TITLE
Add wire debugging functionality

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxNetty#55]
RxNetty should be able to add wire debugging if it is configured to do so as part of `ClientConfig`.

The implementation can probably use Netty's `LoggingHandler`.

**Comment by NiteshKant** [comment]
Makes sense but it should be for both client and server.

**Comment by NiteshKant** [comment]
The way netty's logging handler works is that it logs messages at DEBUG level unless one specifies which level it should log at. So, if logging handler is added to the pipeline, one has to enable logs for the logging handler class at level DEBUG.

One option is to always add LoggingHandler to the pipeline for both client & server. This is not a big deal but may create unnecessary overhead in cases when it is not required.

Other option is to have the LoggingHandler added when clients and servers are created via RxNetty's factory methods. We also provide a utility method to wrap any PipelineConfigurator instance, with one that adds the LoggingHandler. This will make it possible for people to remove the handler if they don't want it and also conveniently add it if they do not use the RxNetty's factory methods for any reason.

**Comment by NiteshKant** [comment]
Both client and server builders now contains a method enableWireLogging(LogLevel) that will add the logging handler in the pipeline with the logging level set as the passed level.

By default RxNetty's factory methods add this handler at log level DEBUG. This means that in order to get these wire level logs, one must set the logging level of package "io.reactivex.netty" to DEBUG.

If this method is called with a level of ERROR then these wire level logs will always be logged which is not at all recommended for production systems due to high verbosity of logs.
