### ISSUE TITLE
RxNetty hangs after sending more than 45 Kbytes of data without flushing

### ISSUE THREAD

**Issue by sdeleuze** [ReactiveX/RxNetty#571]
As demonstrated in this [sample repro project](https://github.com/sdeleuze/rxnetty-send-buffer), RxNetty HTTP server seems to block without sending any data to the client when writing more than approximatively 45 Kbytes, for example when using `ResponseContentWriter#writeString(Observable<String>)`. Maybe the flush triggered by complete is never reached because Netty send buffer is full.

Shouldn't RxNetty handle this case? I would assume RxNetty to auto-flush the data before reaching Netty send buffer limit. If these is expected, could you please explain how can I deal with that use case?

This issue has been discovered as part of Spring Web Reactive benchmarks, see https://jira.spring.io/browse/SPR-14943 for more details.

Thanks in advance for your feedback.

**Comment by NiteshKant** [comment]
>>> Maybe the flush triggered by complete is never reached because Netty send buffer is full.

The problem here is that the source does not complete, due to lack of `requestN` which is caused by write buffer reaching the high watermark.

Good or bad, RxNetty requires explicit flushing and does not do anything related to flushing automagically. I initiated a feature in netty to support `AutoFlush` a while back but it hasn't yet been merged. My take is that these usecases would be handled by `AutoFlush` better, until then you can define your batching strategies using a [flush selector](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-http/src/main/java/io/reactivex/netty/protocol/http/server/ResponseContentWriter.java#L220)

**Comment by sdeleuze** [comment]
Ok thanks for your feedback.

**Comment by sdeleuze** [comment]
@NiteshKant Just a last question, should I expect multiple threads access on a specific flush selector instance created for each write call? I would like to know if [this simple implementation](https://github.com/sdeleuze/spring-framework/blob/24b3614063d5f3318a0242ce62e1f2203e8ead12/spring-web/src/main/java/org/springframework/http/server/reactive/RxNettyServerHttpResponse.java#L124-L142) is ok, or if I should care about concurrent access to `FlushSelector#count`?

**Comment by NiteshKant** [comment]
>> should I expect multiple threads access on a specific flush selector instance created for each write call?

There would not be concurrent access, but you will have to take care of visibility as it may be invoked by different threads at different times.

**Comment by sdeleuze** [comment]
Could you explain what you mean by "you will have to take care of visibility"?

**Comment by NiteshKant** [comment]
@sdeleuze

Flush selector can be invoked by multiple threads but not concurrently. So, if you have shared state, modifications to this state may not be visible across invocations of the flush selector.

**Comment by sdeleuze** [comment]
Ok thanks
