### ISSUE TITLE
0.5 Intuitive bytebuf handling

### ISSUE THREAD

**Issue by joshua-rule** [ReactiveX/RxNetty#599]
Hi,

How valid is the warning against using 0.5.x on production? I really need this feature:
https://github.com/ReactiveX/RxNetty/wiki/0.5.x-FAQs#intuitive-bytebuf-handling

If using 0.5.x is really bad is it still possible to merge the improvement to bytebuf handling into 0.4 possible? 

PS. I am happy to do some work on the project just not sure what the issue is.

Thanks,
Joshua Rule

**Comment by jamesgorman2** [comment]
Hey Joshua,

we've been using 0.5 in production on our product. We're still beta, so low user count but we've shifted a lot of data through it in the last few months. They only trouble we had was a memory leak caused by bot disposing bytebuf's correctly when doing some stream json processing, otherwise it's been rock solid.

Not sure how much mileage you'll get on a 0.4 PR. Nitesh, the maintainer, has not been active on the project recently and I don't know 0.4 well. I have been keeping some stuff ticking over but I'm not a maintainer but am looking at 0.5 -> 1.x (once I have some clear air from day work, it's been held up a lot longer than planned!).

**Comment by joshua-rule** [comment]
Hey James,

Glad to here that you've had some success with 0.5.

Will try it out next week.

Thanks,
Joshua.
