### ISSUE TITLE
AbstractQueueBasedChannelPool issues duplicate channel lifecycle events

### ISSUE THREAD

**Issue by NiteshKant** [ReactiveX/RxNetty#82]
The lifecycle of a channel in netty is defined as 

channelRegistered -> channelActive -> channelInactive -> channeUnregistered

However, going by the code here:

https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/client/pool/AbstractQueueBasedChannelPool.java#L150

The lifecycle will be:

channelRegistered -> channelActive -> channelRegistered -> channelActive -> channelInactive -> channeUnregistered

for the channel that gets reused once.

This will violate the contract of channel lifecycle and hence create confusion for people adding lifecycle handlers to the pipeline.

On a related note, why do we have to re-initialize the pipeline here? As discussed here: https://github.com/Netflix/RxNetty/issues/20 I thought we would not worry about resetting the pipeline and channel states on connection reuse?

**Comment by allenxwang** [comment]
We need to re-initialize pipeline for the following reason:
- Make sure the new Observer is added at the end of the pipeline
- Make sure that custom objects kept in ChannelHandler will no longer be effective (since new instance of ChannelHandler is installed)
- Make the channel reusable for another RxClient that has different pipeline configuration, but talks to the same server.  This is the requirement from higher level client that utilizes the load balancer and share a connection pool for all servers in the farm.

Otherwise, we have to make sure all objects in the ChannelHandler is "resettable" and reset them when a channel is reused, which will make the code complicated.

**Comment by allenxwang** [comment]
Also, since during re-initialization, all channel handlers are removed and new ones are installed, they will not get duplicated channel events. 

https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/client/pool/AbstractQueueBasedChannelPool.java#L146

Specifically, for channel handlers removed during re-initialization, they got:

channelRegistered -> channelActive (assuming the channel was not closed)

For new handlers installed, they will get the same.

I feel this is a simple way to decouple RxClient from handling channel from connection pool as it does not need to do anything special (other than setting an attribute) after getting the channel from the pool.

**Comment by NiteshKant** [comment]
> > > Also, since during re-initialization, all channel handlers are removed and new ones are installed, they will not get duplicated channel events.

You are overlooking the fact that a netty pipeline can have Shared handlers i.e. the same handler instance is used for all channels. If I were to create a shared handler counting number of connections, I will get duplicate events and hence skew my statistics.
Shared handlers are marked with this annotation: https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/ChannelHandler.java#L325

Same instance of the handler will be used by the ChannelInitializer every time it is initialized. So, such a handler will get duplicate events.

As a rule of thumb we should not try to send synthetic events in the pipeline which are supposed to be sent by the framework.

> > > We need to re-initialize pipeline for the following reason

The way re-initialization is done currently is extremely brute force and has unnecessary overheads for the pipelines that do not dynamically modify the pipeline.
As I thought we converged in our discussions in issue #20 that we will have this handled as a best-practice to have any dynamic handlers in the pipeline remove themselves when the request processing is over (connection is returned to the pool). If we were to make this easy, we can fire a custom user event that indicates these handlers to remove themselves from the pipeline.

> > > Make sure the new Observer is added at the end of the pipeline

Are you referring to the ObervableAdapter handler? If yes, then anyone modifying the pipeline should know about the pipeline, someone can not blindly add anything in the pipeline. RxClient and RxServer assures this unless someone dynamically modifies the pipeline. This is a very acceptable practice in any system that implements a chain of responsibility pattern.

> > > Make sure that custom objects kept in ChannelHandler will no longer be effective

ChannelHandlers should manage their state. The current way is just too brute force.

> > > Make the channel reusable for another RxClient that has different pipeline configuration, but talks to the same server. This is the requirement from higher level client that utilizes the load balancer and share a connection pool for all servers in the farm.

Can you explain this more?
Sharing connection pool for a server between different clients create much complex usage pattern. In the bigger picture; we have multiple hystrix commands using multiple ribbon clients using multiple RxClients. In this scenario if we share the connection pool between multiple RxClient, it will become too convoluted to manage the hystrix command pool limits as it is not deterministic as to which command can cannibalize which underlying connections used by another command.
Keeping a connection pool (for a server) tied to an existing RxClient keeps the usage very simple and manageable.

**Comment by allenxwang** [comment]
On the high level, this is what I am trying to achieve:
- Decouple RxClient from connection pool logic, meaning there should be minimal code in RxClient to deal with connection reuse. RxClient does not need to handle channel/pipeline differently if the channel is from the pool vs. a channel created by RxClient itself. A channel should bear minimal state from previous use.
- Keep the code simple and functional initially and optimize later if necessary. 

> > >  If I were to create a shared handler counting number of connections, I will get duplicate events and hence skew my statistics.

User of RxNetty should not feel the presence of connection pool, other than the fact that the connection time is faster. When they would like to open a connection, it should not matter to them whether the connection is from the pool or just created. Therefore, if I were the user, I would expect that connection count is increased even if I am reusing the connection I got from the pool. 

Another question to ask is: should we ask user to write their channelActive() method in consideration of possible use of connection pool? Or it will be better off to tell them it will be called whether the channel is "pre-created" or not. I favor the later, because it may well be a different channel from the last one and to user's perspective, they are getting a new channel to work with.

Also, "Netty In Action" claims that Sharable should only apply to ChannelHandler that is stateless.

> > > As a rule of thumb we should not try to send synthetic events in the pipeline which are supposed to be sent by the framework.

Please let me know where you get this rule. "Netty In Action" explains "fireChannelActive" as this:

This results in having the channelActive(ChannelHandlerContext) method called of the next ChannelInboundHandler in the ChannelPipeline. 

There is no any hint or suggestion that this should not be called by user of Netty. In addition, we are transitioning the channel from "idle" to "active". So to me, we are taking advantages of the Netty public API that allows us to trigger state change of the ChannelHandler. Note that we are not violating the state model for the ChannelHandler either.

> > > Are you referring to the ObervableAdapter handler? If yes, then anyone modifying the pipeline should know about the pipeline, someone can not blindly add anything in the pipeline.

I am not referring to people dynamically modifying the pipeline. Our own handlers and observers are stateful. Consider a user submits a second request and subscribes a new Observer with the same RxClient. Now, am I right that a lot of things in our own handlers in the pipeline has to be reset if we want to reuse the channel and pipeline? For example, bridgedObserver in the ObserverAdapter, inputSubject in ConnectionLifecycleHandler, contentSubject and requestProcessingObserver in ClientRequestResponseConverter. I think a clean and simple way to deal with that complexity is to reinitialize the pipeline with new handlers. 

> > > As I thought we converged in our discussions in issue #20 that we will have this handled as a best-practice to have any dynamic handlers in the pipeline remove themselves when the request processing is over (connection is returned to the pool). 

The best-practice is one solution. But I often found it is not effective as it can be easily lost in communication.  In the end, we will have to debug problems caused by not following best practice.

So if we can have a solution that does not require "best-practice", I would go for it.

> > > In this scenario if we share the connection pool between multiple RxClient, it will become too convoluted to manage the hystrix command pool limits as it is not deterministic as to which command can cannibalize which underlying connections used by another command.

We do not share pool across hystrix command. One Ribbon client should manage one connection pool which is shared among the RxClients it creates. This is the current way Hystrix/Ribbon/Connection pool interacts.

**Comment by NiteshKant** [comment]
After changes in pull request #95 it is not required for the channel pipeline to be re-created. All RxNetty added handlers are suitable for connection re-use.

Any handler which is added or modified dynamically, must listen to [ConnectionReuseEvent](https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/client/ConnectionReuseEvent.java), which is emitted before a connection is reused and do anything necessary for connection reusability with the perspective of that handler.
