### ISSUE TITLE
Move host and port to RxClient method signature

### ISSUE THREAD

**Issue by allenxwang** [ReactiveX/RxNetty#88]
Currently host and port are required arguments for the constructor and instance variables for RxClientImpl. I am proposing moving them to method signature like connect() or submit(). This will have the following benefit:
- Makes RxClient reusable when it needs to connect to a different server but uses the same client and pipeline configuration
- Makes it possible to have APIs that support full HTTP URI that includes host and port
- Provides an easier way to integrate with Ribbon load balancer which provides host and port.

**Comment by benjchristensen** [comment]
Right now it is this awkward design:

``` java
HttpClient<ByteBuf, ByteBuf> client = RxNetty.createHttpClient("localhost", 8080);

client.submit(HttpClientRequest.createGet("/"));
```

I assume you mean we'd instead do something like:

``` java
HttpClient<ByteBuf, ByteBuf> client = RxNetty.createHttpClient();

client.submit(HttpClientRequest.createGet("http://localhost:8080/")));
// which can be aliased for the GET case as
client.get("http://localhost:8080/"));
```

**Comment by NiteshKant** [comment]
The model that RxClient has now is that an RxClient implementation must connect to either one (the current implementation) or a group of "homogeneous" servers. 

I guess there are two distinct type of users of RxClient (with respect to this discussion):
- _Casual users_: Users who are playing with RxNetty with an intent of experimentation/learning.
-  _Production applications_: Applications based on higher level clients like ribbon. 

In ribbon as we do today, we create ribbon clients for a group of homogeneous servers. Grouping can be based on VIPs, applications, clusters, asgs, etc. but all the servers are homogeneous. What this essentially means that while executing a request, the user does not specify a host/port. All they do is; ask ribbon to execute this request on "any server" in the farm. This kind of groupings inside clients is certainly natural because the client configurations (eg: connection timeouts, read timeouts, etc.) are best configured for a homogeneous set of servers.
RxClient follows this model targeting mainly users in the second category above.

Now, ribbon (atleast inside Netflix) marries these two usecases by giving the ability to pass a VIP address or a host in the URL, but that comes with a complexity of analysing the URL, trying to match with a VIP address or other criterion to decide if this is a host or not.

I have tried to stay away from this approach sighting simplicity in design. Having said that, if we were to create a client that can connect to a set of heterogenous servers, we can surely do that by creating an abstraction on top of these clients with a slightly different API (of passing host/port) which internally is a composite of individual RxClients specific to different host/port combinations.

To make the users in the first category happier we can provide simple shorthands like RxNetty.get() RxNetty.post() if that pleases everyones tastebuds :) Such a shorthand will use the composite client I mentioned above.

**Comment by benjchristensen** [comment]
> I guess there are two distinct type of users

There will be production applications that use RxNetty directly. Mantis is one of them.

**Comment by NiteshKant** [comment]
PR #120 adds a method:

```
public static Observable<HttpClientResponse<ByteBuf>> createHttpRequest(HttpClientRequest<ByteBuf> request) {
```

which can be used as:

```
RxNetty.createHttpRequest(HttpClientRequest.createGet("http://localhost:8080/hello")).subscribe()
```

to execute a request with the full HTTP uri.

**Comment by NiteshKant** [comment]
So I added the following shorthand methods to RxNetty to alleviate this concern.

-- [RxNetty.createHttpGet()](https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/RxNetty.java#L167)
Example:

```
HttpClientResponse<ByteBuf> response = RxNetty.createHttpGet("http://localhost:8080/hello").toBlockingObservable().last();
```

-- [RxNetty.createHttpPost()](https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/RxNetty.java#L171)
Example:

```
        ContentSource.SingletonSource<ByteBuf> content = new ContentSource.SingletonSource<ByteBuf>(
                Unpooled.buffer().writeBytes("Hello!".getBytes()));
        HttpClientResponse<ByteBuf> response =
                RxNetty.createHttpPost("http://localhost:8080/helloPost", content).toBlockingObservable().last();

```

-- [RxNetty.createHttpPut()](https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/RxNetty.java#L175)
Example:

```
        ContentSource.SingletonSource<ByteBuf> content = new ContentSource.SingletonSource<ByteBuf>(
                Unpooled.buffer().writeBytes("Hello!".getBytes()));
        HttpClientResponse<ByteBuf> response =
                RxNetty.createHttpPut("http://localhost:8080/helloPut", content).toBlockingObservable().last();

```

-- [RxNetty.createHttpDelete()](https://github.com/Netflix/RxNetty/blob/master/rx-netty/src/main/java/io/reactivex/netty/RxNetty.java#L187)
Example:

```
HttpClientResponse<ByteBuf> response = RxNetty.createHttpDelete("http://localhost:8080/helloDelete").toBlockingObservable().last();
```

**Comment by NiteshKant** [comment]
I am not completely satisfied with this approach as if someone has to manipulate the request before sending, it is impossible to do so.
I will close this as of now and then propose something that can make this better. As of now, this alleviates the usability concern discussed in this bug.
