### ISSUE TITLE
Adding Headers Before Flush Still Doesn't Add Them

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxNetty#91]
If I write anything to the channel and then add headers (even without flushing) the headers don't show up. 

The use case is placing headers after we're finish writing that give the server-side duration (we do this all over Netflix). 

If we flush manually, then this is impossible of course, but if we don't flush and add a header before closing then the headers should show up.

**Comment by NiteshKant** [comment]
This is interesting. 

So, what happens now is that the writeXXX calls actually write the content on the socket. In order to confirm with HTTP, we have to write the headers first. 
Now, if we have to allow writing headers after writing the content, we have two choices:
- Buffer the content and headers till a flush is issued. When a flush is issued, we write everything on the socket.
- Write these headers after the content is written and force the HTTP transfer encoding as "chunked".

If we have to buffer, we should possibly have an explicit indication instead of it being the default, but that gets pretty convoluted. 
Writing headers after content, with chunked encoding seems cleaner but not many people do so.

Thoughts?

**Comment by benjchristensen** [comment]
I thought it wouldn't write to the socket until flush was called?

What is the current difference between write and writeAndFlush?

**Comment by NiteshKant** [comment]
I should have been clearer. When I said "writeXXX calls actually write the content on the socket" I meant "writeXXX calls actually write the content on netty's channel"

A writeXXX call invokes write() on netty's channel which executes the pipeline and adds the obtained ByteBuf to the channel's write buffer. When flush() is called on that channel, it is actually writes to the underlying socket.

So, from the application standpoint, after we do a write on the netty's channel for the headers and content, we can't write any more headers unless we do what I have mentioned in the previous comment.

**Comment by benjchristensen** [comment]
This sounds rather awkward to deal with because it would mean we're buffering writes somewhere else and then buffer yet again after we flush/close as it hits the channel. Surely there is a better way to get a header in place before a flush goes out? There are many Netflix apps that rely on this type of behavior so we need a solution for this that isn't breaking the performance benefits we're seeking for.

**Comment by NiteshKant** [comment]
> > > This sounds rather awkward to deal with because it would mean we're buffering writes somewhere else and then buffer yet again after we flush/close as it hits the channel.

Exactly, thats why I was not inclined towards choice 1 I stated as it creates two queuing points; one our response object and then the selector's queue.

> > > Surely there is a better way to get a header in place before a flush goes out?

Since, as soon as we write to netty's channel, the object traverses the pipeline and hence gets converted to a ByteBuf, we semantically can't write any more headers.
However, what we can write are the headers after the content is written a.k.a. trailing headers in an HTTP chunk. The issue is that the system reading these header values must be aware of the fact that they are coming as trailing headers. It is debatable but we may create a plumbing to seamlessly show these trailing headers as part of the main headers, provided that they are queried after the response is complete.

**Comment by NiteshKant** [comment]
@benjchristensen ... ping...

**Comment by NiteshKant** [comment]
0.5.x cleans up the interaction model with HTTP response. There were issues in the API earlier where someone can set headers -> write content -> update headers. The second update of headers would not work as the headers are already sent.

In 0.5.x, after writing the content, headers updates are not allowed.
